"""empty message

Revision ID: 2f5f145433dd
Revises: 3a594df6407b
Create Date: 2024-02-19 14:42:36.436968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5f145433dd'
down_revision = '3a594df6407b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
