"""Add eraser clicks to User

Revision ID: a2ac4cbef8bd
Revises: a92e4c095080
Create Date: 2024-02-06 14:40:43.921909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ac4cbef8bd'
down_revision = 'a92e4c095080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eraser_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('eraser_clicks')

    # ### end Alembic commands ###
