"""Add delete all clicks to User

Revision ID: cfa723bd2c07
Revises: a2ac4cbef8bd
Create Date: 2024-02-06 15:06:19.706578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa723bd2c07'
down_revision = 'a2ac4cbef8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_all_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('delete_all_clicks')

    # ### end Alembic commands ###
