"""Add screenshot path to User

Revision ID: fe2ef7a82f8d
Revises: 638c5abe4dfa
Create Date: 2024-02-08 15:11:09.030814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2ef7a82f8d'
down_revision = '638c5abe4dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('screenshot_path')

    # ### end Alembic commands ###
