"""Add delete all clicks to User

Revision ID: 209ac09ff100
Revises: ad4a4a58a7fd
Create Date: 2024-02-06 15:06:30.436294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209ac09ff100'
down_revision = 'ad4a4a58a7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_all_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('delete_all_clicks')

    # ### end Alembic commands ###
