"""Add eraser clicks to User

Revision ID: ad4a4a58a7fd
Revises: 2d00efb2cd46
Create Date: 2024-02-06 14:41:00.213961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4a4a58a7fd'
down_revision = '2d00efb2cd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eraser_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('eraser_clicks')

    # ### end Alembic commands ###
