"""Add message count to User

Revision ID: 0132ff9c0c47
Revises: 36fa5e025082
Create Date: 2024-02-06 15:27:41.376647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0132ff9c0c47'
down_revision = '36fa5e025082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('message_count')

    # ### end Alembic commands ###
