"""Add delete all clicks to User

Revision ID: 36fa5e025082
Revises: 4f4dba82002d
Create Date: 2024-02-06 15:06:03.323518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fa5e025082'
down_revision = '4f4dba82002d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_all_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('delete_all_clicks')

    # ### end Alembic commands ###
