"""Add eraser clicks to User

Revision ID: 4f4dba82002d
Revises: 3ea256cf0afd
Create Date: 2024-02-06 14:21:40.943662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4dba82002d'
down_revision = '3ea256cf0afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eraser_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('eraser_clicks')

    # ### end Alembic commands ###
