"""empty message

Revision ID: 8bfad68d93e8
Revises: 0132ff9c0c47
Create Date: 2024-02-08 15:30:06.136656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfad68d93e8'
down_revision = '0132ff9c0c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('screenshot_path')

    # ### end Alembic commands ###
